-- Giám đốc
CREATE ROLE giamdoc WITH LOGIN SUPERUSER CREATEDB CREATEROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO giamdoc;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO giamdoc;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO giamdoc;
GRANT CREATE ON SCHEMA public TO giamdoc;
CREATE USER nv01 WITH PASSWORD 'mk_nv01';
GRANT giamdoc TO nv01;
-- Phó Giám đốc
CREATE ROLE phoGiamdoc WITH LOGIN CREATEROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE HangHoa TO phoGiamdoc;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE KhachHang TO phoGiamdoc;
GRANT SELECT, INSERT, UPDATE ON TABLE ChiTietHoaDon TO phoGiamdoc;
GRANT SELECT, INSERT, UPDATE ON TABLE HoaDon TO phoGiamdoc;
GRANT SELECT, UPDATE ON TABLE NhanVien TO phoGiamdoc;
GRANT SELECT, UPDATE ON TABLE ThongTinLuong TO phoGiamdoc;
GRANT SELECT ON TABLE CTGiamGia TO phoGiamdoc;
GRANT SELECT ON TABLE Kho TO phoGiamdoc;
CREATE USER nv03 WITH PASSWORD 'mk_nv03';
GRANT phoGiamdoc TO nv03;

-- Cửa hàng trưởng
CREATE ROLE cuaHangTruong WITH LOGIN;
GRANT SELECT, INSERT, UPDATE ON TABLE ChiTietHoaDon TO cuaHangTruong;
GRANT SELECT, INSERT, UPDATE ON TABLE HoaDon TO cuaHangTruong;
GRANT SELECT, INSERT, UPDATE ON TABLE KhachHang TO cuaHangTruong;
GRANT SELECT ON TABLE CTGiamGia TO cuaHangTruong;
GRANT SELECT ON TABLE HangHoa TO cuaHangTruong;
CREATE USER nv08 WITH PASSWORD 'mk_nv08';
GRANT cuaHangTruong TO nv08;
CREATE USER nv09 WITH PASSWORD 'mk_nv09';
GRANT cuaHangTruong TO nv09;
CREATE USER nv19 WITH PASSWORD 'mk_nv19';
GRANT cuaHangTruong TO nv19;
-- Nhân viên bán hàng
CREATE ROLE nhanVienBanHang WITH LOGIN;
GRANT SELECT ON TABLE ChiTietHoaDon TO nhanVienBanHang;
GRANT SELECT ON TABLE CTGiamGia TO nhanVienBanHang;
GRANT SELECT ON TABLE HangHoa TO nhanVienBanHang;
GRANT SELECT ON TABLE HoaDon TO nhanVienBanHang;
GRANT SELECT ON TABLE KhachHang TO nhanVienBanHang;
CREATE USER nv10 WITH PASSWORD 'mk_nv10';
GRANT nhanVienBanHang TO nv10;
CREATE USER nv11 WITH PASSWORD 'mk_nv11';
GRANT nhanVienBanHang TO nv11;
CREATE USER nv12 WITH PASSWORD 'mk_nv12';
GRANT nhanVienBanHang TO nv12;
CREATE USER nv13 WITH PASSWORD 'mk_nv13';
GRANT nhanVienBanHang TO nv13;
CREATE USER nv20 WITH PASSWORD 'mk_nv20';
GRANT nhanVienBanHang TO nv20;
CREATE USER nv23 WITH PASSWORD 'mk_nv23';
GRANT nhanVienBanHang TO nv23;
CREATE USER nv24 WITH PASSWORD 'mk_nv24';
GRANT nhanVienBanHang TO nv24;
CREATE USER nv25 WITH PASSWORD 'mk_nv25';
GRANT nhanVienBanHang TO nv25;
CREATE USER nv26 WITH PASSWORD 'mk_nv26';
GRANT nhanVienBanHang TO nv26;
CREATE USER nv29 WITH PASSWORD 'mk_nv29';
GRANT nhanVienBanHang TO nv29;
CREATE USER nv30 WITH PASSWORD 'mk_nv30';
GRANT nhanVienBanHang TO nv30;
CREATE USER nv31 WITH PASSWORD 'mk_nv31';
GRANT nhanVienBanHang TO nv31;
CREATE USER nv32 WITH PASSWORD 'mk_nv32';
GRANT nhanVienBanHang TO nv32;
CREATE USER nv33 WITH PASSWORD 'mk_nv33';
GRANT nhanVienBanHang TO nv33;
CREATE USER nv34 WITH PASSWORD 'mk_nv34';
GRANT nhanVienBanHang TO nv34;
CREATE USER nv35 WITH PASSWORD 'mk_nv35';
GRANT nhanVienBanHang TO nv35;
CREATE USER nv36 WITH PASSWORD 'mk_nv36';
GRANT nhanVienBanHang TO nv36;
CREATE USER nv37 WITH PASSWORD 'mk_nv37';
GRANT nhanVienBanHang TO nv37;
CREATE USER nv38 WITH PASSWORD 'mk_nv38';
GRANT nhanVienBanHang TO nv38;
CREATE USER nv39 WITH PASSWORD 'mk_nv39';
GRANT nhanVienBanHang TO nv39;
CREATE USER nv40 WITH PASSWORD 'mk_nv40';
GRANT nhanVienBanHang TO nv40;
CREATE USER nv45 WITH PASSWORD 'mk_nv45';
GRANT nhanVienBanHang TO nv45;
CREATE USER nv46 WITH PASSWORD 'mk_nv46';
GRANT nhanVienBanHang TO nv46;

-- Trưởng phòng kế toán
CREATE ROLE truongPhongKeToan WITH LOGIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ChiTietHoaDon TO truongPhongKeToan;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE HoaDon TO truongPhongKeToan;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE LuongThang TO truongPhongKeToan;
GRANT SELECT, INSERT, UPDATE ON TABLE CTGiamGia TO truongPhongKeToan;
GRANT SELECT, INSERT, UPDATE ON TABLE ThongTinLuong TO truongPhongKeToan;
GRANT SELECT ON TABLE HangHoa TO truongPhongKeToan;
GRANT SELECT ON TABLE KhachHang TO truongPhongKeToan;
CREATE USER nv04 WITH PASSWORD 'mk_nv04';
GRANT truongPhongKeToan TO nv04;
-- Nhân viên kế toán
CREATE ROLE nhanVienKeToan WITH LOGIN;
GRANT SELECT, INSERT ON TABLE ChiTietHoaDon TO nhanVienKeToan;
GRANT SELECT, INSERT ON TABLE HoaDon TO nhanVienKeToan;
GRANT SELECT ON TABLE CTGiamGia TO nhanVienKeToan;
GRANT SELECT ON TABLE HangHoa TO nhanVienKeToan;
GRANT SELECT ON TABLE LuongThang TO nhanVienKeToan;
CREATE USER nv14 WITH PASSWORD 'mk_nv14';
GRANT nhanVienKeToan TO nv14;
CREATE USER nv47 WITH PASSWORD 'mk_nv47';
GRANT nhanVienKeToan TO nv47;

-- Trưởng phòng kỹ thuật
CREATE ROLE truongPhongKyThuat WITH LOGIN;
GRANT SELECT, INSERT, UPDATE ON TABLE HangHoa TO truongPhongKyThuat;
GRANT SELECT ON TABLE ChiTietHoaDon TO truongPhongKyThuat;
GRANT SELECT ON TABLE CTGiamGia TO truongPhongKyThuat;
GRANT SELECT ON TABLE Kho TO truongPhongKyThuat;
CREATE USER nv07 WITH PASSWORD 'mk_nv07';
GRANT truongPhongKyThuat TO nv07;
-- Nhân viên kỹ thuật
CREATE ROLE nhanVienKyThuat WITH LOGIN;
GRANT SELECT ON TABLE HangHoa TO nhanVienKyThuat;
GRANT SELECT ON TABLE Kho TO nhanVienKyThuat;
GRANT SELECT ON TABLE CTGiamGia TO nhanVienKyThuat;
CREATE USER nv15 WITH PASSWORD 'mk_nv15';
GRANT nhanVienKyThuat TO nv15;
CREATE USER nv48 WITH PASSWORD 'mk_nv48';
GRANT nhanVienKyThuat TO nv48;

-- Trưởng phòng nhân sự
CREATE ROLE truongPhongNhanSu WITH LOGIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE NhanVien TO truongPhongNhanSu;
GRANT SELECT, INSERT, UPDATE ON TABLE PhongBan TO truongPhongNhanSu;
GRANT SELECT, INSERT, UPDATE ON TABLE ThongTinLuong TO truongPhongNhanSu;
GRANT SELECT ON TABLE KhachHang TO truongPhongNhanSu;
GRANT SELECT ON TABLE LuongThang TO truongPhongNhanSu;
CREATE USER nv05 WITH PASSWORD 'mk_nv05';
GRANT truongPhongNhanSu TO nv05;
-- Chuyên viên nhân sự
CREATE ROLE chuyenVienNhanSu WITH LOGIN;
GRANT SELECT, INSERT, UPDATE ON TABLE NhanVien TO chuyenVienNhanSu;
GRANT SELECT, INSERT, UPDATE ON TABLE PhongBan TO chuyenVienNhanSu;
GRANT SELECT ON TABLE ThongTinLuong TO chuyenVienNhanSu;
CREATE USER nv22 WITH PASSWORD 'mk_nv22';
GRANT chuyenVienNhanSu TO nv22;

-- Trưởng phòng bảo vệ
CREATE ROLE truongPhongBaoVe WITH LOGIN;
GRANT SELECT ON TABLE Kho TO truongPhongBaoVe;
GRANT SELECT ON TABLE NhanVien TO truongPhongBaoVe;
CREATE USER nv17 WITH PASSWORD 'mk_nv17';
GRANT truongPhongBaoVe TO nv17;
-- Bảo vệ
CREATE ROLE baoVe WITH LOGIN;
GRANT SELECT ON TABLE Kho TO baoVe;
GRANT SELECT ON TABLE NhanVien TO baoVe;
CREATE USER nv02 WITH PASSWORD 'mk_nv02';
GRANT baoVe TO nv02;
CREATE USER nv27 WITH PASSWORD 'mk_nv27';
GRANT baoVe TO nv27;
CREATE USER nv28 WITH PASSWORD 'mk_nv28';
GRANT baoVe TO nv28;
CREATE USER nv41 WITH PASSWORD 'mk_nv41';
GRANT baoVe TO nv41;
CREATE USER nv42 WITH PASSWORD 'mk_nv42';
GRANT baoVe TO nv42;
CREATE USER nv44 WITH PASSWORD 'mk_nv44';
GRANT baoVe TO nv44;
CREATE USER nv50 WITH PASSWORD 'mk_nv50';
GRANT baoVe TO nv50;

-- Trưởng phòng quản lý Kho
CREATE ROLE truongPhongKho WITH LOGIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE Kho TO truongPhongKho;
GRANT SELECT, INSERT, UPDATE ON TABLE CTGiamGia TO truongPhongKho;
GRANT SELECT, UPDATE ON TABLE HangHoa TO truongPhongKho;
GRANT SELECT ON TABLE ChiTietHoaDon TO truongPhongKho;
CREATE USER nv06 WITH PASSWORD 'mk_nv06';
GRANT truongPhongKho TO nv06;
CREATE USER nv16 WITH PASSWORD 'mk_nv16';
GRANT truongPhongKho TO nv16;
-- Quản lý Kho
CREATE ROLE quanLyKho WITH LOGIN;
GRANT SELECT, INSERT, UPDATE ON TABLE HangHoa TO quanLyKho;
GRANT SELECT, INSERT, UPDATE ON TABLE Kho TO quanLyKho;
GRANT SELECT ON TABLE CTGiamGia TO quanLyKho;
CREATE USER nv18 WITH PASSWORD 'mk_nv18';
GRANT quanLyKho TO nv18;
CREATE USER nv21 WITH PASSWORD 'mk_nv21';
GRANT quanLyKho TO nv21;

-- Nhân viên pháp lý
CREATE ROLE nhanVienPhapLy WITH LOGIN;
GRANT SELECT ON TABLE ChiTietHoaDon TO nhanVienPhapLy;
GRANT SELECT ON TABLE HoaDon TO nhanVienPhapLy;
GRANT SELECT ON TABLE KhachHang TO nhanVienPhapLy;
GRANT SELECT ON TABLE NhanVien TO nhanVienPhapLy;
CREATE USER nv43 WITH PASSWORD 'mk_nv43';
GRANT nhanVienPhapLy TO nv43;
CREATE USER nv49 WITH PASSWORD 'mk_nv49';
GRANT nhanVienPhapLy TO nv49;

-- Hạn chế quyền truy cập PUBIC
REVOKE ALL ON DATABASE Nhom29 FROM PUBLIC;